In [1]:
import sys
sys.path.insert(0, '..')
from utils.cargar import df_caso
from utils.preprocesamiento import process_df, procesar_adela

caso = 'adela'
df = df_caso(caso,chat=True)
df.head()

,user_id,team_id,gender,df,title,opt_left,opt_right,message,phase,time,reply_to,curso
id,,,,,,,,,,,,
91531,9490,3900.0,M,1,"[Acordar entre todas/os la respuesta, discutie...",Preservar el recurso natural escaso.,Beneficiar la salud de niños y ancianos.,hola,3,2023-06-16T19:16:28.204Z,NaN,2023.CD1100
91532,9505,3886.0,M,1,"[Acordar entre todas/os la respuesta, discutie...",Preservar el recurso natural escaso.,Beneficiar la salud de niños y ancianos.,hola amigos,3,2023-06-16T19:16:29.065Z,NaN,2023.CD1100
91533,9506,3888.0,M,1,"[Acordar entre todas/os la respuesta, discutie...",Preservar el recurso natural escaso.,Beneficiar la salud de niños y ancianos.,Hola,3,2023-06-16T19:16:30.668Z,NaN,2023.CD1100
91534,9506,3888.0,M,1,"[Acordar entre todas/os la respuesta, discutie...",Preservar el recurso natural escaso.,Beneficiar la salud de niños y ancianos.,Hola,3,2023-06-16T19:16:31.576Z,NaN,2023.CD1100
91535,9513,3902.0,M,1,"[Acordar entre todas/os la respuesta, discutie...",Preservar el recurso natural escaso.,Beneficiar la salud de niños y ancianos.,Hoola karlota,3,2023-06-16T19:16:31.939Z,NaN,2023.CD1100

In [3]:
df['phase'].value_counts()

phase
3    7656
2    6674
Name: count, dtype: int64

In [4]:
df.to_csv("datos_EthicApp/MDS7201/{}_chat.csv".format(caso))