In [1]:
import sys
sys.path.insert(0, '..')
from utils.cargar import df_caso
from utils.preprocesamiento import process_df, procesar_adela

caso = 'adela'
df = df_caso(caso,verbose=True)

df = procesar_adela(df)
df = process_df(df,'comment','sel')
# df = df[df['opt_left'] == 'Producir el alimento contra déficit vitamínico']

df.head()

Secciones encontradas:
	 2021.CD2201.15.A2.csv
	 2021.CD2201.14.A2.csv
	 2021.CD2201.28.A2.csv
	 2021.CD2201.02.A2.csv
	 2021.CD2201.13.A2.csv
	 2021.CD2201.07.A2.csv
	 2021.CD2201.05.A2.csv
	 2021.CD2201.09.A2.csv
	 2021.CD2201.10.A2.csv
	 2021.CD2201.01.A2.csv
	 2021.CD2201.06.A2.csv
	 2022.CD1201.2.csv
	 2022.CD1201.5.csv
	 2022.CD1201.8.csv
	 2022.CD1201.9.csv
	 2022.CD1201.3.csv
	 2022.CD1201.6.csv
	 2022.CD1201.4.csv
	 2022.CD1201.7.csv
	 2022.CD1201.10.csv
	 2022.CD1201.1.csv
	 2023.CD1100.8.csv
	 2023.CD1100.4.csv
	 2023.CD1100.6.csv
	 2023.CD1100.10.csv
	 2023.CD1100.5.csv
	 2023.CD1100.2.csv
	 2023.CD1100.3.csv
	 2023.CD1100.7.csv
	 2023.CD1100.9.csv


75 rows found with non string elements for column comment (0.58%)
Deleting 1055 columns for which max target value is over 7 (8.16%)
11803 available rows after processing

,user_id,team_id,gender,df,title,opt_left,opt_right,max_num,sel,comment,phase,time,curso,seccion
id,,,,,,,,,,,,,,
26261,4238,NaN,M,1,Adela es una ingeniera que es parte de una sta...,Preservar el recurso natural escaso,Beneficiar la salud de niños y ancianos,6,3,A pesar de que es importante la salud de esa p...,1,2021-11-10T21:00:31.008Z,2021.CD2201,14
26262,4227,NaN,F,1,Adela es una ingeniera que es parte de una sta...,Preservar el recurso natural escaso,Beneficiar la salud de niños y ancianos,6,1,Creo que debería priorizar totalmente preserva...,1,2021-11-10T21:03:04.192Z,2021.CD2201,14
26264,4232,NaN,F,1,Adela es una ingeniera que es parte de una sta...,Preservar el recurso natural escaso,Beneficiar la salud de niños y ancianos,6,1,Existen otras fuentes de vitamina D o podrían ...,1,2021-11-10T21:03:31.124Z,2021.CD2201,14
26265,4239,NaN,M,1,Adela es una ingeniera que es parte de una sta...,Preservar el recurso natural escaso,Beneficiar la salud de niños y ancianos,6,2,dañar una localidad completa limitándoles el u...,1,2021-11-10T21:03:36.038Z,2021.CD2201,14
26267,4231,NaN,M,1,Adela es una ingeniera que es parte de una sta...,Preservar el recurso natural escaso,Beneficiar la salud de niños y ancianos,6,2,A mi modo de ver preservar el recurso natural ...,1,2021-11-10T21:04:14.600Z,2021.CD2201,14

In [2]:
df['phase'].value_counts()

phase
3    3238
2    3017
4    3015
1    2123
5     180
6     180
7      50
Name: count, dtype: int64

In [3]:
print(df['title'].unique()[-1])
print('1\t'+df['opt_left'].unique()[-1])
print(str(df['max_num'].unique()[-1])+'\t'+df['opt_right'].unique()[-1])

[Acordar entre todas/os la respuesta, discutiendo vía chat de forma anónima, aspectos ya considerados u otros no considerados en las preguntas anteriores. Es decir, todos deben elegir el mismo valor numérico en la respuesta, aun cuando cada uno pueda proporcionar argumentos de justificación diferentes] [Justificación de mínimo 40 palabras] Considerando la futura población beneficiada por este nuevo alimento y los efectos generados a las tradiciones identitarias del pueblo originario del caso, Adela debería priorizar... :
1	Producir el alimento contra déficit vitamínico
6	Resguardar las tradiciones identitarias

In [4]:
df['opt_left'].value_counts()

opt_left
Preservar el recurso natural escaso               6042
Producir el alimento contra déficit vitamínico    5761
Name: count, dtype: int64

Agregando la etapa de actividad

In [5]:
from utils.cargar import columna_fase

df = columna_fase(df,'adela')

df['etapa'].value_counts()

etapa
Grup    3430
Ind1    3214
Ind2    3183
Name: count, dtype: int64

In [6]:
df.to_csv("datos_EthicApp/MDS7201/{}.csv".format(caso))

---

In [7]:
caso = 'alicia'
df = df_caso(caso,verbose=True)

df = process_df(df,'comment','sel')

df.head()

Secciones encontradas:
	 2021.CD1201.07.CAL.A1.csv
	 2021.CD1201.02.CAL.A2.csv
	 2021.CD1201.09.CAL.A2.csv
	 2021.CD1201.08.CAL.A2.csv
	 2021.CD1201.06.CAL.A3.csv
	 2021.CD1201.01.CAL.A2.csv
	 2021.CD1201.06.CAL.A1.csv
	 2021.CD1201.06.CAL.A2.csv
	 2021.CD1201.09.CAL.A1.csv
	 2021.CD1201.09.CAL.A3.csv
	 2021.CD1201.07.CAL.A3.csv
	 2021.CD1201.05.CAL.A2.csv
	 2021.CD1201.01.CAL.A3.csv
	 2021.CD1201.08.CAL.A3.csv
	 2021.CD1201.02.CAL.A3.csv
	 2021.CD1201.03.CAL.A3.csv
	 2021.CD1201.05.CAL.A1.csv
	 2021.CD1201.03.CAL.A2.csv
	 2021.CD1201.05.CAL.A3.csv
	 2021.CD1201.07.CAL.A2.csv
	 2021.CD1201.03.CAL.A1.csv
	 2021.CD1201.04.CAL.A1.csv
	 2021.CD1201.04.CAL.A2.csv
	 2021.CD1201.04.CAL.A3.csv
	 2022.CD1100.06.csv
	 2022.CD1100.07.csv
	 2022.CD1100.10.csv
	 2022.CD1100.06.E0.csv
	 2022.CD1100.08.csv
	 2022.CD1100.02.csv
	 2022.CD1100.07.E0.csv
	 2022.CD1100.09.csv
	 2022.CD1100.05.E0.csv
	 2022.CD1100.01.csv
	 2022.CD1100.03.csv
	 2022.CD1100.10.E0.csv
	 2022.CD1100.05.csv


80 rows found with non string elements for column comment (0.65%)
Deleting 2326 columns for which max target value is over 7 (18.76%)
9991 available rows after processing

,user_id,team_id,gender,df,title,opt_left,opt_right,max_num,sel,comment,phase,time,curso,seccion
id,,,,,,,,,,,,,,
20310,2870,NaN,M,2,[Proporcione argumentos para justificar su res...,Los criterios técnicos del proyecto y de los u...,Los plazos acordados del proyecto,6,1,entrega de producto defectuoso no cumple con l...,1,2021-10-27T01:26:34.475Z,2021.CD1201,7
20311,2870,NaN,M,1,[Proporcione argumentos para justificar su res...,Por sobre cualquier otra consideración,Supeditado a las condiciones contextuales,6,1,se debe recuperar tiempo perdido,1,2021-10-27T01:26:35.637Z,2021.CD1201,7
20314,3339,NaN,M,1,[Proporcione argumentos para justificar su res...,Por sobre cualquier otra consideración,Supeditado a las condiciones contextuales,6,3,"Una contexto como es el de pandemia, es algo m...",1,2021-10-27T03:07:50.378Z,2021.CD1201,7
20315,3339,NaN,M,2,[Proporcione argumentos para justificar su res...,Los criterios técnicos del proyecto y de los u...,Los plazos acordados del proyecto,6,3,Debiese priorizar cumplir con los criterios té...,1,2021-10-27T03:07:52.002Z,2021.CD1201,7
20400,2695,NaN,F,1,[Proporcione argumentos para justificar su res...,Por sobre cualquier otra consideración,Supeditado a las condiciones contextuales,6,4,Lo mejor sería intentar apurar un poco el proy...,1,2021-10-28T15:39:02.170Z,2021.CD1201,7

In [8]:
def procesar_alicia(df):
    # procesamiento especial caso Alicia
    df.loc[df['opt_left']=='Por sobre  cualquier otra  consideración','opt_left'] = 'Por sobre cualquier otra consideración'
    df.loc[df['opt_left']=='Los criterios  técnicos del  proyecto y de los  usuarios','opt_left'] = 'Los criterios técnicos del proyecto y de los usuarios'

    df.loc[df['opt_right']=='Supeditado a las  condiciones  contextuales','opt_right'] = 'Supeditado a las condiciones contextuales'
    df.loc[df['opt_right']=='Los plazos  acordados del  proyecto'] = 'Los plazos acordados del proyecto'

    df = df[df['opt_right'] != df['opt_left']]

    return df

df = procesar_alicia(df)

df['opt_right'].value_counts()

opt_right
Los plazos acordados del proyecto                                       4892
Tratar de mantener su reputación personal, profesional y empresarial    2643
Supeditado a las condiciones contextuales                               2358
Name: count, dtype: int64

In [9]:
df['opt_left'].value_counts()

opt_left
Los criterios técnicos del proyecto y de los usuarios    4892
Transparencia al mandante y los usuarios                 2643
Por sobre cualquier otra consideración                   2358
Name: count, dtype: int64

In [10]:
from utils.cargar import columna_fase

df = columna_fase(df,'alicia')

df['etapa'].value_counts()

etapa
Ind1    3615
Grup    2228
Ind2    1606
Name: count, dtype: int64

In [11]:
df['etapa'].isna().sum()

2444

In [12]:
df.to_csv("datos_EthicApp/MDS7201/{}.csv".format('alicia'))

---

Julieta

In [13]:
caso = 'julieta'
df = df_caso(caso,verbose=True)

df = process_df(df,'comment','sel')

df.head()

Secciones encontradas:
	 2021.CD1100.01.CJ.A1.csv
	 2021.CD1100.04.CJ.A2.csv
	 2021.CD1100.07.CJ.A1.csv
	 2021.CD1100.03.CJ.A2.csv
	 2021.CD1100.07.CJ.A2.csv
	 2021.CD1100.08.CJ.A3.csv
	 2021.CD1100.08.CJ.A1.csv
	 2021.CD1100.09.CJ.A2.RZ.csv
	 2021.CD1100.09.CJ.A1.csv
	 2021.CD1100.08.CJ.A2.csv
	 2021.CD1100.03.CJ.A3.csv
	 2021.CD1100.06.CJ.A1.csv
	 2021.CD1100.03.CJ.A1.csv
	 2021.CD1100.02.CJ.A3.csv
	 2021.CD1100.04.CJ.A1.csv
	 2021.CD1100.04.CJ.A3.csv
	 2021.CD1100.07.CJ.A3.csv
	 2021.CD1100.09.CJ.A3.csv
	 2021.CD1100.01.CJ.A2.csv
	 2021.CD1100.09.CJ.A2.csv
	 2021.CD1100.02.CJ.A2.csv
	 2021.CD1100.01.CJ.A3.csv
	 2021.CD1100.09.CJ.A1.RZ.csv
	 2021.CD1100.06.CJ.A2.csv
	 2021.CD1100.06.CJ.A3.csv


34 rows found with non string elements for column comment (0.67%)
Deleting 255 columns for which max target value is over 7 (5.00%)
4806 available rows after processing

,user_id,team_id,gender,df,title,opt_left,opt_right,max_num,sel,comment,phase,time,curso,seccion
id,,,,,,,,,,,,,,
11511,2695,NaN,F,1,[Proporcione argumentos para justificar su res...,Usar la información del grupo de WhatsApp,No usar la información del grupo de WhatsApp,6,6,Si estudiaste y sabes hacer los ejercicios ¿pa...,1,2021-05-19T02:23:09.528Z,2021.CD1100,1
11515,2702,NaN,F,1,[Proporcione argumentos para justificar su res...,Usar la información del grupo de WhatsApp,No usar la información del grupo de WhatsApp,6,5,No debería usar la información ya que no es co...,1,2021-05-19T02:49:39.214Z,2021.CD1100,1
11516,2701,NaN,F,1,[Proporcione argumentos para justificar su res...,Usar la información del grupo de WhatsApp,No usar la información del grupo de WhatsApp,6,4,si es que no sabe realizar la pregunta puede r...,1,2021-05-19T02:49:40.029Z,2021.CD1100,1
11517,2700,NaN,F,1,[Proporcione argumentos para justificar su res...,Usar la información del grupo de WhatsApp,No usar la información del grupo de WhatsApp,6,3,lamentablemente este pais es muy injusto y la ...,1,2021-05-19T02:53:11.462Z,2021.CD1100,1
11519,2707,NaN,M,1,[Proporcione argumentos para justificar su res...,Usar la información del grupo de WhatsApp,No usar la información del grupo de WhatsApp,6,6,Considerando que Julieta pudo optar por una be...,1,2021-05-19T03:16:45.404Z,2021.CD1100,1

In [14]:
def procesar_julieta(df):
    # procesamiento especial caso Julieta
    df.loc[df['opt_left']=='Usar la información del grupo de WhatsApp','opt_left'] = 'Usar información del grupo de WhatsApp'

    df.loc[df['opt_right']=='No usar la información del  grupo de WhatsApp','opt_right'] = 'No usar la información del grupo de WhatsApp'

    return df

df = procesar_julieta(df)

df['opt_left'].value_counts()

opt_left
Usar información del grupo de WhatsApp    4806
Name: count, dtype: int64

In [15]:
from utils.cargar import columna_fase

df = columna_fase(df,'julieta')

df['etapa'].value_counts()

etapa
Ind1    766
Grup    755
Ind2    750
Name: count, dtype: int64

In [16]:
df['etapa'].isna().sum()

2535

In [17]:
df.to_csv("datos_EthicApp/MDS7201/{}.csv".format(caso))

---
Laura

In [18]:
caso = 'laura'
df = df_caso(caso,verbose=True)

df = process_df(df,'comment','sel')

df.head()

Secciones encontradas:
	 2020.CD2201.01.A2.csv
	 2020.CD2201.10.A2.csv
	 2020.CD2201.07.A2.csv
	 2020.CD2201.24.A2.csv
	 2020.CD2201.28.A2.csv
	 2020.CD2201.25.A2.csv
	 2020.CD2201.04.A2.csv
	 2020.CD2201.22.A2.RZ3.csv
	 2020.CD2201.22.A2.RZ2.csv
	 2020.CD2201.09.A2.csv
	 2020.CD2201.13.A2.csv
	 2020.CD2201.16.A2.csv
	 2020.CD2201.23.A2.csv
	 2020.CD2201.12.A2.csv
	 2020.CD2201.27.A2.csv
	 2020.CD2201.22.A2.RZ.csv
	 2020.CD2201.06.A2.csv
	 2020.CD2201.26.A2.csv
	 2020.CD2201.18.A2.csv


549 rows found with non string elements for column comment (11.03%)
Deleting 362 columns for which max target value is over 7 (7.27%)
4067 available rows after processing

,user_id,team_id,gender,df,title,opt_left,opt_right,max_num,sel,comment,phase,time,curso,seccion
id,,,,,,,,,,,,,,
4580,1495,NaN,F,2,Respecto de los ingenieros que renuncian al pr...,Renunciar al proyecto,Quedarse en el proyecto,6,4,Depende del nivel de impacto del proyecto en p...,1,2020-09-26T16:11:47.483Z,2020.CD2201,1
4582,1576,NaN,M,2,Respecto de los ingenieros que renuncian al pr...,Renunciar al proyecto,Quedarse en el proyecto,6,2,No marco 1 porque de quedarse podrían haber ay...,1,2020-09-26T16:11:59.096Z,2020.CD2201,1
4588,1550,NaN,F,2,Respecto de los ingenieros que renuncian al pr...,Renunciar al proyecto,Quedarse en el proyecto,6,1,Creo que ninguna persona debería trabajar en u...,1,2020-09-26T16:12:41.957Z,2020.CD2201,1
4589,1495,NaN,F,3,Fue adecuado que Laura ante al error cometido ...,Fue adecuado,No fue adecuado,6,6,"Ya que Laura, informó su error, se hizo respon...",1,2020-09-26T16:12:52.882Z,2020.CD2201,1
4593,1478,NaN,M,2,Respecto de los ingenieros que renuncian al pr...,Renunciar al proyecto,Quedarse en el proyecto,6,2,A pesar de que por parte de la empresa se seña...,1,2020-09-26T16:13:01.297Z,2020.CD2201,1

In [19]:
def procesar_laura(df):
    # procesamiento especial caso Laura
    df.loc[df['opt_left']=='Usar la información del grupo de WhatsApp','opt_left'] = 'Usar información del grupo de WhatsApp'

    df.loc[df['opt_right']=='No usar la información del  grupo de WhatsApp','opt_right'] = 'No usar la información del grupo de WhatsApp'

    # df = df[df['opt_right'] != df['opt_left']]

    return df

df = procesar_laura(df)

df['opt_left'].value_counts()

opt_left
Renunciar al proyecto                   1377
Fue adecuado                            1258
Ajustar dedicación                      1134
na                                       119
x                                         54
no aplica                                 50
Si considere sus opiniones                30
Aprendí algo e influyó en mi postura      27
1                                         18
Name: count, dtype: int64

In [20]:
df['opt_right'].value_counts()

opt_right
Quedarse en el proyecto          1377
No fue adecuado                  1258
Mantener dedicación              1134
na                                119
x                                  54
no aplica                          50
No, solo considere mi opinion      30
No aprendí ni me influyó           27
2                                  18
Name: count, dtype: int64

In [21]:
from utils.cargar import columna_fase

df = columna_fase(df,'laura')

df['etapa'].value_counts()

Series([], Name: count, dtype: int64)

In [22]:
df['etapa'].isna().sum()

4067

In [23]:
df.to_csv("datos_EthicApp/MDS7201/{}.csv".format(caso))